backend:
  name: github
  repo: ViruOne/idealaqua
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Mahsulotlar"
    folder: "public/data/products"
    json_backlink: "public/data/products.json"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Nomi", name: "title", widget: "string" }
      - { label: "Kategoriya", name: "category", widget: "string" }
      - { label: "Narxi (so'm)", name: "price", widget: "number", value_type: "int" }
      - { label: "Rasm", name: "image", widget: "image", required: false }
      - { label: "Tavsif", name: "body", widget: "text", required: false }
